# Generated by Django 5.2.1 on 2025-06-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_end_product_discount_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
    ]
