# Generated by Django 5.2.1 on 2025-06-25 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new_arrival',
        ),
    ]
